### ISSUE TITLE
META-INF/MANIFEST.MF is missing

### ISSUE THREAD

**Issue by AminLA** [tesla/m2eclipse-mavenarchiver#5]
@eClipse 4.4 M3(m2e 1.5.0.20131109-1116) 
each time we build our maven project(via Build Automatically, not from maven command)

META-INF/MANIFEST.MF will also be generated at target folder with specified maven-jar-plugin manifestEntries configuration

but eClipse 4.4 M7(m2e 1.5.0.20140505) no longer generate META-INF/MANIFEST.MF (via Build Automatically)

is this a bug or behavior changed(work as design) ?

@see https://bugs.eclipse.org/bugs/show_bug.cgi?id=434818

**Comment by fbricon** [comment]
This was fixed a while ago. You can install the latest version from http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-mavenarchiver/0.17.0/N/LATEST/

**Comment by shashanksinghal** [comment]
I updated the plugin but still MANIFEST.MF not generating for me.

Using STS 3.6.4 release with eclipse 4.4.2. m2e version is 1.5.2.
