### ISSUE TITLE
org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter) error with maven-jar-plugin 3.0.1

### ISSUE THREAD

**Issue by jansohn** [tesla/m2eclipse-mavenarchiver#9]
I'm using the latest version (https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.1/N/LATEST/) of the m2e-archiver posted here (https://github.com/tesla/m2eclipse-mavenarchiver/issues/8) which fixed an error for maven-jar-plugin 3.0.0.
When I switch to latest version 3.0.1 I get a new error: `org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter)`

Similar problem? Can you take a look at it?

I'm using:

- Eclipse: 4.5.2.20160218-0600
- m2e connector for mavenarchiver: 0.17.1.201605251832
- JDK: 1.8.0_71 (32bit)

**Comment by fbricon** [comment]
Please try the CI build from https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/

**Comment by theit** [comment]
I also had this error (see m2e-users mailing list), and with this build it disappears. Thanks for the fast update!

**Comment by jansohn** [comment]
Works, thanks for the quick fix!

**Comment by runeflobakk** [comment]
I experience this error (`org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter)`) in Eclipse Neon with m2eclipse-mavenarchiver 0.17.2 installed. I happens with maven-jar-plugin 3.0.2 and 3.0.1, but not 3.0.0.

If it helps at all, this is my installed m2e-related components:
<img width="1053" alt="m2e" src="https://cloud.githubusercontent.com/assets/174823/16715693/eb34e6f6-46e7-11e6-9dbd-5e610896a85d.png">



Interestingly, I do not experience the error in Eclipse Mars.

**Comment by fbricon** [comment]
Can you provide a sample project reproducing this issue?

**Comment by runeflobakk** [comment]
Well, on my end, all it takes is a freshly new project with nothing more in the `pom.xml` than this:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>some.groupid</groupId>
    <artifactId>my-artifact</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.0.2</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```
It happens both when importing the Maven project into my existing workspace (with lots of projects and various altered configuration), and a new empty workspace from scratch. Are there any logs or something I can look at with more information than just `org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter)`?

**Comment by jansohn** [comment]
I don't experience this error with Eclipse Neon, m2eclipse-mavenarchiver 0.17.2 and maven-jar-plugin 3.0.2. That fresh Eclipse Neon installation would be a good idea, I guess!

**Comment by dantran** [comment]
I am seeing same issue with eclispe Neon + takari-team.  Installing the suggested from https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/  does not help. It removed my takari-team and but does not solve the issue

**Comment by dantran** [comment]
actually it works, but removing my takari team feature is kind a strange

**Comment by runeflobakk** [comment]
I am not able to reproduce the issue with a clean install of Eclipse Neon. I have no idea what could have triggered it in my previous Neon-installation. 🤔

**Comment by dantran** [comment]
I install takari-team on top of  neon.  I also check takari-team feature, it uses and older version of m2e maven archiver

**Comment by khmarbaise** [comment]
I can acknowledge that this state works with Eclipse Neon (4.6.0) with Maven Jar Plugin 3.0.2. Thanks for fixing this.

**Comment by dantran** [comment]
looks like i am the only one using takari-team on top of eclipse( neon)??

**Comment by fbricon** [comment]
ping @jvanzyl ^^

**Comment by ManfredTremmel** [comment]
I do have the same problem in Eclipse Neon (4.6.0) with Maven Jar Plugin 3.0.2 on Linux (Debian 8 64Bit). Maybe you can reproduce it with my [mt-bean-validators](https://github.com/ManfredTremmel/mt-bean-validators) project.

**Comment by khmarbaise** [comment]
@ManfredTremmel Why do you have configured jackrabbit as extension in your build? I don't see the need for this? I have made a PR to improve your build and follow more convention over configuration...I have checked your build with Eclipse Neon and it works perfect without any issue..

**Comment by fbricon** [comment]
@ManfredTremmel have you installed https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/ ?

**Comment by ManfredTremmel** [comment]
@khmarbaise I've added the jackrabbit extension when I've configured automatic deployment to maven repository. I'm not realy sure, but I think, I've followed the solution on http://stackoverflow.com/questions/21902873/automate-deployment-to-sonatypes-oss-maven-repository
I'll try your changes, if upload works without jackrabbit, I've nothing against removing it.

@fbricon My fault, I've updated the plugin and the error is gone. Thank you

**Comment by matthewlowry** [comment]
Just for the record - I hit this issue too and can confirm fixed for me in 0.17.2.201606141937

**Comment by dantran** [comment]
Talaria folks are under deep see 😱

**Comment by iyustlop** [comment]
I'm starting on maven I've include maven-jar-plugin and I have this error. I'm using Lubuntu  x86_64 with eclipse NEON 4.6.0.

My project is "hello world" from maven-archetype-quickstart. 

<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.0.2</version>
        <configuration>
          <archive>
+			<manifest>
+				<addClasspath>true</addClasspath>
+				<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
+				<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
+			</manifest>
+		</archive> 
        </configuration>
      </plugin>

I hope you could guide to solve my problem.

Thank you very much in advance.

**Comment by matthewlowry** [comment]
@iyustlop Hopefully you can solve this problem by updating to the latest 0.17.2 version of `m2eclipse-mavenarchiver`

Install the latest version by using `https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/` as the update site. (Use the "Install new software..." menu, paste this URL into to the "Work with" text box, and install the "m2e extensions" plugins.)

**Comment by roizpi** [comment]
Still is occurring to me, with this snippet:
`<plugin>`
			`	<groupId>org.apache.maven.plugins</groupId>`
`				<artifactId>maven-compiler-plugin</artifactId>`
	`			<version>3.5.1</version>`
		`		<configuration>`
			`		<source>1.8</source>`
				`	<target>1.8</target>`
				`</configuration>`
		`	</plugin>`
But solved with the aforementioned *Manual* update .

**Comment by tkruse** [comment]
Same here, compiler plugin 3.5.1, but only when using in combination with maven-jar-plugin:3.x.x or maven-war-plugin:3.x.x. 

As a workaround, I can use:

    maven-jar-plugin:2.4
    maven-war-plugin:2.6

**Comment by earcam** [comment]
It's unclear when users of vanilla Eclipse Neon will receive this fix.  Can you please advise?



Minimal POM to reproduce:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>gitub</groupId>
	<artifactId>meh</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<packaging>jar</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

 			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>3.2.0</version>
				<extensions>true</extensions>
				<configuration>
					<archive>
						<addMavenDescriptor>true</addMavenDescriptor>
					</archive>
					<supportedProjectTypes>
						<supportedProjectType>jar</supportedProjectType>
					</supportedProjectTypes>
					<instructions>
						<Bundle-Category>${project.groupId}</Bundle-Category>
						<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
						<Bundle-Version>${project.version}</Bundle-Version>
					</instructions>
				</configuration>
				<executions>
					<execution>
						<id>create-manifest</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>manifest</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.0.2</version>
				<configuration>
					<archive>
						<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

Alternative, remove maven-bundle-plugin and add src/main/resources/META-INF/MANIFEST.MF - Alt-F5 to m2e refresh project and same result.


Based on, vanilla setup:
Eclipse: Neon 4.6.0, build ID; 20160613-1800
M2E: 1.7.20160603-1933



Thanks

**Comment by fbricon** [comment]
Neon.1 will be released on Sept 28th, 2016. See https://wiki.eclipse.org/Neon/Simultaneous_Release_Plan#Neon.1

**Comment by earcam** [comment]
@fbricon perfect, thank you.  Only a week to wait =)

**Comment by Sevyls** [comment]
Hi!
I upgraded yesterday to Eclipse Neon.1 and I am still receiving this error:

Description	Resource	Path	Location	Type
org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter)	pom.xml	/***-app	line 1	Maven Configuration Problem

eclipse.buildId=4.6.1.M20160907-1200

m2e connector for mavenarchiver pom properties	0.17.2.201606141937-signed-20160830073346	org.sonatype.m2e.mavenarchiver.feature.feature.group	Sonatype, Inc.
![image](https://cloud.githubusercontent.com/assets/547842/18951425/72e457b6-8645-11e6-8840-c8fe643c45d2.png)

![image](https://cloud.githubusercontent.com/assets/547842/18951514/e2086010-8645-11e6-976f-893d9edfc157.png)

Please assist.

**Comment by jjayaraman** [comment]
Any solution for this error.... ? I too get this in my pom.xml in Eclipse Neon.

**Comment by fbricon** [comment]
@Sevyls I can't reproduce the issue, please attach a sample project so that I can investigate.

@jjayaraman did you try Neon.1? Make sure you have m2eclipse-mavenarchiver 0.17.2 installed

**Comment by runeflobakk** [comment]
I had this error earlier on Eclipse Neon as well, with the connector available from the 0.17.2 url previously given in this thread. After reinstalling Neon, and installing the connector v0.17.2 the problem went away. Don't know what initially caused it.

@Sevyls I see you have 0.17.2.201606141937, while I have 1.17.2.201609252051 (and Neon.1). Did you install the connector from the given url?

**Comment by hmmlopez** [comment]
Actually I get the same error as soon as i put the following in the pom.xml

`<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-war-plugin</artifactId>
	<version>3.0.0</version>
</plugin>`

Maybe a conflict somewhere? Don't know if this helps but I saw it mentioned above also.
Version: Neon Release (4.6.0)
Build id: 20160613-1800
M2E version: 1.7.0.20160603-1933

**Comment by mdarifmustafa** [comment]
Same issue were occuring for me, pom.xml overview showing error org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter) and really confused what did the mistake I have made in pom.xml or some other thing!

Same after I googled and found this issue thread, and thus by reducing the Maven Jar plugin version to 3.0.0 from 3.0.2, the overview error resolved, just like that -

```
<project xmlns="http://maven.apache.org/POM/4.0.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.whodesire.upattern</groupId>
  <artifactId>Pattern</artifactId>
  <version>2017.11.001</version>
  <name>UPattern</name>
  <description>Provide 2D Swing Pattern Lock Facility</description>
  
  <build>
    <plugins>
    	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<version>3.5.1</version>
		<configuration>
			<source>1.7</source>
			<target>1.7</target>
		</configuration>
	</plugin>
    	<plugin>
      		<groupId>org.apache.maven.plugins</groupId>
        	<artifactId>maven-jar-plugin</artifactId>
  		<version>3.0.0</version>
        	<configuration>
        		<source>1.7</source>
          		<target>1.7</target>
          		<archive>
				<manifest>
                    			<mainClass>com.whodesire.upattern.Pattern</mainClass>
                		</manifest>
            		</archive>
        	</configuration>
      	</plugin>
  	</plugins>
  </build>
  
  <organization>
  	<name>Whodesire Solutions</name>
  	<url>www.whodesire.com</url>
  </organization>
</project>
```

**Comment by Patekar** [comment]
I am facing "org.codehaus.plexus.archiver.jar.Manifest.write(java.io.PrintWriter)" error in my pom.xml file.
Below is the xml file:
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.globant.automation</groupId>
	<artifactId>test-project</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.1.RELEASE</version>
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.globant.automation</groupId>
			<artifactId>test-framework</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M2</version>
				<configuration>
					
					<suiteXmlFiles>
						<suiteXmlFile>src/main/resources/testng.xml</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
![mvn](https://user-images.githubusercontent.com/34711992/62215789-358ef000-b3c5-11e9-8192-b938ccfcbb82.JPG)

I am using Eclipse Version: Neon Release (4.6.0).
